#!/bin/sh -x 
uvccapture -odownfacing.jpg -v -x1280 -y960 -d/dev/video1 -B128 -C40 -S40 -G1 

cat TopMask.gbr | ./gerbertojpg 0 0
./crosshair

fbi -T 2 -a down.jpg
cp down.jpg /var/www/down.jpg
sleep 2
pkill fbi 

