#!/usr/bin/env perl
use PNP::Feeder;

my $feeder = new PNP::Feeder( refdes => 'C1' );

$feeder->x0(0);
$feeder->y0(0);
$feeder->z0(0);
$feeder->a0(0);

$feeder->x1(36);
$feeder->y1(4.9);
$feeder->z1(0.1);
$feeder->a1(0);

$feeder->count(10);

foreach my $x (0..9) {
	$feeder->pointer($x);
	my ($x, $y, $z, $a) = $feeder->getCoord();

	printf("%0.2f %0.2f %0.2f %0.2f\n", $x, $y, $z, $a);

}

